vanguardbackup/vanguard

app/Actions/RemoteServer/RemoveSSHKey.php
app/Http/Controllers/RemoteServers/EditController.php
app/Jobs/RemoteServers/RemoveSSHKeyJob.php
app/Jobs/RemoteServers/RemoveServerJob.php
app/Livewire/RemoteServers/DeleteRemoteServerForm.php
app/Livewire/RemoteServers/IndexTable.php
app/Mail/RemoteServers/FailedToRemoveKey.php
app/Mail/RemoteServers/SuccessfullyRemovedKey.php
app/Models/RemoteServer.php
database/migrations/2024_06_14_162816_add_marked_for_deletion_at_to_remote_servers_table.php
resources/views/livewire/backup-tasks/run-task-button.blade.php
resources/views/livewire/remote-servers/delete-remote-server-form.blade.php
resources/views/mail/remote-servers/failed-to-remove-key.blade.php
resources/views/mail/remote-servers/successfully-removed-key.blade.php
tests/Feature/RemoteServers/Livewire/DeleteRemoteServerFormTest.php
tests/Feature/RemoteServers/Pages/EditPageTest.php
tests/Unit/RemoteServerTest.php

This PR introduces SSH key removal, as a side effect I moved server deletion into a job to give the SSH key deletion job time to execute with the model data.
I primarily wanted this so it could "clean up" after itself, should people not want to have the app connected to their remote server anymore.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

Feat: SSH Key Removal

---

app/Console/Commands/SendPersonalAccessTokenExpiringSoon.php
app/Mail/PersonalAccessTokenExpiringSoonMail.php
app/Models/PersonalAccessToken.php
database/factories/PersonalAccessTokenFactory.php
database/migrations/2024_08_14_095006_add_last_notification_sent_to_personal_access_token_table.php
resources/views/livewire/profile/api-token-manager.blade.php
resources/views/mail/personal-access-token-expiring-soon.blade.php
routes/console.php
tests/Feature/Console/Commands/SendPersonalAccessTokenExpiringSoonTest.php
tests/Feature/Profile/ApiTokenManagerTest.php
tests/Unit/Models/PersonalAccessTokenTest.php

Adds the option for api tokens to expire after a certain period of time, with email notifications just before the token is deleted.
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

feat: API Token Expiry

---

.github/workflows/pest-tests.yml
app/Livewire/Profile/SessionsPage.php
composer.json
composer.lock
config/session.php
resources/views/account/partials/sidebar.blade.php
resources/views/livewire/profile/session-manager.blade.php
resources/views/livewire/profile/sessions-page.blade.php
routes/breadcrumbs.php
routes/web.php
tests/Feature/Profile/SessionTest.php

This PR adds session management if the session driver is set to 'database', which is the default one but it can be overriden.
Please also include relevant motivation and context if possible.

feat: Session management

---

.github/workflows/duster-fix-blame.yml
.github/workflows/prettier.yml

There is a workflow error when attempting to run workflows on PR branches, this PR aims to resolve those errors.

fix: PR workflows failing

---

bootstrap/app.php
composer.json
composer.lock
config/sentry.php

This adds Sentry to the application for error logging - has been a long time coming but I kept forgetting to do so.

chore: Added sentry

---

lang/da.json
resources/views/livewire/backup-destinations/create-backup-destination-form.blade.php

Adds a little notice when creating a backup destination that states we encrypt all credentials passed to the form. 
- [] I have added tests that prove my fix is effective or that my feature works

feat: Add notice

---

resources/views/components/dropdown-link.blade.php
resources/views/components/dropdown.blade.php
resources/views/livewire/layout/navigation.blade.php

Minor icon changes and style improvements to the user dropdown. Also fixed the broken instance details link on mobile while I was at it.

style: Tweaks to user dropdown

---

.github/pull_request_template.md

PR template needed some adjustments.

chore: Update pr template

---

lang/da.json
resources/views/livewire/remote-servers/create-remote-server-form.blade.php

The old connection failed screen was pretty basic and it needed some love. This one includes some tips depending on the failure reason as well.

style: Update the connection failed screen

---

lang/da.json
resources/views/layouts/app.blade.php

With 2025 near the corner, the footer has been updated to include the start year. 

chore: Add start year to footer

---

resources/views/livewire/profile/connections-page.blade.php

Fixes the style issues with the element, it didn't have a dark mode variant and it looked slightly wonky.
(Before)
(After)

style: Updated external connection ui

---

composer.lock
package-lock.json

chore: update dependencies

---

resources/views/layouts/app.blade.php

This PR adds a link to the changelog for the specific version of the software to the footer.

feat: Add github version link to footer

---

app/Http/Controllers/BackupTasks/TriggerRunWebhookController.php
app/Livewire/BackupTasks/Modals/WebhookModal.php
app/Models/BackupTask.php
bootstrap/app.php
database/migrations/2025_02_27_184529_add_webhook_token_to_backup_tasks_table.php
resources/views/livewire/backup-tasks/modals/webhook-modal.blade.php
resources/views/livewire/backup-tasks/tables/index-item.blade.php
routes/web.php
tests/Feature/BackupTasks/Webhooks/BackupTaskWebhookTest.php
tests/Unit/Models/BackupTaskTest.php

This PR introduces the ability to trigger a backup task execution via a POST request to the specified URL endpoint.

feat: Added webhook task run trigger

---

resources/views/livewire/backup-tasks/tables/index-table.blade.php

The initial design for the filter system was very much a first pass, this is much better from a UI/UX POV.

style: Redesigned filters

---

app/Http/Middleware/EnforceTwoFactor.php
tests/Feature/Auth/TwoFactorTest.php

We've been dealing with intermittent issues with two-factor being too aggressive and triggering when it shouldn't. This hopes to resolve these issues.
-

fix: Resolve two-factor being too aggressive

---

app/Http/Controllers/BackupTasks/TriggerRunWebhookController.php
app/Models/BackupTask.php
database/factories/BackupTaskFactory.php
database/migrations/2025_02_28_002511_add_webhook_last_used_to_backup_tasks_table.php
resources/views/livewire/backup-tasks/modals/webhook-modal.blade.php
tests/Feature/BackupTasks/Webhooks/BackupTaskWebhookTest.php
tests/Unit/Models/BackupTaskTest.php

Adds a timestamp when successful requests to the webhook are made.

feat: add webhook last used indicator

---

resources/views/livewire/remote-servers/create-remote-server-form.blade.php

Improving the design, layout and information provided.

style: improved connection screens

---

app/Actions/LoadScheduledBackupTasksAction.php
app/Http/Controllers/Api/ScheduledBackupTasksController.php
app/Http/Resources/ScheduledBackupTaskResource.php
app/Livewire/BackupTasks/Tables/BackupTaskHistoryItem.php
app/Livewire/Dashboard/UpcomingBackupTasks.php
routes/api.php
tests/Feature/BackupTasks/Api/BackupTaskScheduledListTest.php
tests/Feature/BackupTasks/Webhooks/BackupTaskWebhookTest.php
tests/Unit/Models/BackupTaskTest.php

This will add an endpoint to the API `/api/backup-tasks/upcoming` which lists the backup tasks that are scheduled to be ran in the future. (Same as Overview page!)

feat: Add endpoint for upcoming backup tasks

---

app/Models/BackupTask.php
app/Models/Traits/HasNotificationStream.php
app/Models/Traits/NotificationStreamable.php

Extracted Notification Streams into their own trait, it will eventually be moved into the Services folder but this is a good half-way point.

refactor: notification streams

---

app/Mail/User/WelcomeMail.php
resources/views/mail/backup-connection-failure.blade.php
resources/views/mail/user/device-authentication-log-in.blade.php
resources/views/mail/user/quiet-mode-expired-mail.blade.php
resources/views/mail/user/summary-backup-mail.blade.php
resources/views/mail/user/two-factor/admin-disabled-two-factor-mail.blade.php
resources/views/mail/user/two-factor/disabled-mail.blade.php
resources/views/mail/user/two-factor/enabled-mail.blade.php
resources/views/mail/user/two-factor/longstanding-two-factor-follow-up-mail.blade.php
resources/views/mail/user/two-factor/low-backup-codes-notice-mail.blade.php
resources/views/mail/user/two-factor/no-backup-codes-remaining-notice-mail.blade.php
resources/views/mail/user/two-factor/regenerated-backup-codes-mail.blade.php
resources/views/mail/user/two-factor/viewed-backup-codes-mail.blade.php
resources/views/mail/user/welcome-mail.blade.php
tests/Feature/Auth/WelcomeMailTest.php
tests/Feature/Mail/SummaryBackupMailTest.php

The ending message of mailables were often pretty inconsistent, this aims to address that.

fix: make mailables consistent

---

resources/views/account/partials/sidebar.blade.php
resources/views/components/form-wrapper.blade.php
resources/views/dashboard.blade.php
resources/views/livewire/dashboard/upcoming-backup-tasks.blade.php
resources/views/livewire/profile/help-page.blade.php
resources/views/livewire/profile/update-profile-information-form.blade.php
resources/views/partials/breadcrumbs.blade.php
routes/breadcrumbs.php

Improved some parts of the app that needed some attention UI wise. Most notably the help page.

Improved various pages

---

app/Models/BackupTask.php
app/Models/RemoteServer.php
app/Models/User.php

Added the missing fields to the exclusion array, to ensure they won't be audited erroneously.

fix: Add missing fields to exclusion 

---

app/Mail/User/DeletionConfirmationMail.php
composer.lock
resources/views/livewire/profile/delete-user-form.blade.php
resources/views/mail/user/deletion-confirmation-mail.blade.php
tests/Feature/Profile/ProfileTest.php

Sends an email to the user informing them of their account erasure.

feat: Send email when a user deletes their account
